# The time goes in seconds
TIME-TO-KICK: 30

KICK-MESSAGE:
  TIME: '&c&lYou took too long to complete the captcha! Try again.'
  BAD-ITEM: '&c&lYou did not pass the captcha challenge, try again'

CAPTCHA-PASSED: '&aYou successfully passed the captcha'

MENU-TITLE: '&eComplete captcha'